---
- name: Configure nginx.conf
  template: src={{ ansible_os_family }}/nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Configure routing.conf
  template: src={{ ansible_os_family }}/routing.conf.j2 dest=/etc/nginx/conf.d/routing.conf

- name: Configure magento virtual host magento.conf
  template: src={{ ansible_os_family }}/magento.conf.j2 dest=/etc/nginx/conf.d/magento.conf
