---
#- name: restart apache
#  service: name=apache2 state=restarted
#  when: ansible_os_family == 'Debian'

- name: restart php-fpm
  service: name=php-fpm state=restarted
  ignore_errors: yes

- name: restart nginx
  service: name=nginx state=restarted
